#!/bin/bash

# colors
cp -v Resesif.dvtcolortheme ~/Library/Developer/Xcode/UserData/FontAndColorThemes/Resesif.dvtcolortheme

# keybindings
cp -v DefaultKeyBinding.dict ~/Library/KeyBindings/DefaultKeyBinding.dict

# vim
cp -v .vimrc ~/.vimrc
vim +NeoBundleInstall +qall
sh ~/.vim/bundle/YouCompleteMe/install.sh --clang-completer --omni-sharp-completer

# zshrc
cp -v .zshrc ~/.zshrc

# gitconfig
cp -v .gitconfig ~/.gitconfig

