#!/bin/bash

# colors
cp -vaf  colors-xcode/. ~/Library/Developer/Xcode/UserData/FontAndColorThemes
cp -v colors-xcode/Resesif.dvtcolortheme ~/Library/Developer/Xcode/UserData/FontAndColorThemes

# keybindings
cp -v DefaultKeyBinding.dict ~/Library/KeyBindings/DefaultKeyBinding.dict

# vim
cp -v .vimrc ~/.vimrc
vim +NeoBundleInstall +qall

# zshrc
cp -v .zshrc ~/.zshrc

# gitconfig
cp -v .gitconfig ~/.gitconfig

# hydra
cp -v -r .hydra ~/.hydra
