#!/bin/bash

cp -v  ~/.vimrc .vimrc
cp -v ~/.xvimrc .xvimrc
cp -v ~/.zshrc .zshrc
cp -v ~/Library/KeyBindings/DefaultKeyBinding.dict DefaultKeyBinding.dict
cp -v ~/.gitconfig .gitconfig
cp -vaf ~/Library/Developer/Xcode/UserData/FontAndColorThemes/. colors-xcode

